### ISSUE TITLE
Add Fedisearch

### ISSUE THREAD

**Issue by TheEvilSkeleton** [searx/searx#2335] opened 2020-11-27 02:31 UTC
Link: https://fedisearch.com/

**Comment by dalf** [comment] 2020-11-27 10:40
It seems offline:
![image](https://user-images.githubusercontent.com/1594191/100440530-52b0fd00-30a5-11eb-8497-a677eb0565d3.png)

**Comment by virtadpt** [comment] 2020-11-27 21:26
It's back up.  Might have been a hiccough.

**Comment by dalf** [comment] 2020-12-02 08:11
For some reason I always get the same page (different IP, different browsers, different OS)
If I use curl, it works.
I see this website is using Cloudfront. I expect a CAPTCHA problem.

**Comment by unixfox** [comment] 2020-12-02 08:44
> For some reason I always get the same page (different IP, different browsers, different OS)
> If I use curl, it works.
> I see this website is using Cloudfront. I expect a CAPTCHA problem.

Could you try on a fresh browser without any extensions? It does work fine on my part.

**Comment by dalf** [comment] 2020-12-02 09:04
URL https://fedisearch.com/ same error with:
* Linux, FF 83, Private browsing, no extension
* Android 8, FF nightly
* Android 8, Chrome last version

The issue seems to be `Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3`

Fix either:
* if I add `?locale=en` as a query parameter.
* if I change my locale to `en-US` in the browser.

**Comment by return42** [comment] 2020-12-02 09:13
> if I add ?locale=en as a query parameter.

I tried 'fr' and got the same *"We're sorry..*" message as @dalf .. very strange.

**Comment by Broeckelmann** [comment] 2020-12-03 13:27
If got no problems with fedisearch.com

**Comment by tiotrom** [comment] 2020-12-12 14:27
Works for me. Linux, FF 83.

**Comment by return42** [comment] 2020-12-12 17:18
> Works for me. Linux, FF 83.

Language?  .. Language seems the problem, read https://github.com/searx/searx/issues/2335#issuecomment-737093393

**Comment by tiotrom** [comment] 2020-12-14 14:48
EN

**Comment by sebilasse** [comment] 2021-01-26 17:49
@return42 The problem is that the query itself needs to have the default language added like e.g. :  

https://fedisearch.com/search?q=YOURSEARCHQUERY&commit=Search&locale=en

For example 
https://fedisearch.com/search?q=activitypub&commit=Search&locale=en

**Comment by return42** [comment] 2021-01-26 20:47
As normal user, why should I handcraft a URL when I just want to open the search dialog?

What is the advantage of Fedisearch compared to other search sides? IMO Fedisearch is crap .. but if someone wants to implement an searx-engine for .. why not.

**Comment by sebilasse** [comment] 2021-01-27 04:28
Well, I agree that Fedisearch is crap.

Personally I applied for funding for Search and the Fediverse and Searx and redaktor.
I just wanted to help and show the bug after your 3 messages here [:))] by analysing the error which is just there is no default locale. 
Sorry.

**Comment by return42** [comment] 2021-01-27 05:10
@sebilasse It is not about you .. we never got any comments from the opener .. just two words "add xyz" and a link to a crappy search engine .. no reason named why we should implement a scraper for .. 

I vote to close such noise issues before me and you are wasting more time with.

**Comment by sebilasse** [comment] 2021-01-27 05:13
close +1
Also: Duplicate of https://github.com/searx/searx/issues/906

**Comment by return42** [comment] 2021-03-30 08:19
Can we close this issue? (duplicate: #906)

**Closed as completed** 2021-03-30 10:32 UTC
Labels: engine request
