### ISSUE TITLE
'images' [500 internal server error]

### ISSUE THREAD

**Issue by fabionar** [searx/searx#1074] opened 2017-10-29 13:19 UTC
```
[2017-10-29 06:15:78,547] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch
_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_e
xception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch
_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_requ
est
    return self.view_functions[rule.endpoint](**req.view_args)
  File "webapp.py", line 572, in index
    favicons=global_favicons[themes.index(get_current_theme_name())]
  File "webapp.py", line 383, in render
    '{}/{}'.format(kwargs['theme'], template_name), **kwargs)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 134, in render_
template
    context, ctx.app)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 116, in _render

    rv = template.render(context)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 1008, in rend
er
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 780, in handl
e_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\searx\templates\oscar\results.html", line
9, in top-level template code
    {%- macro search_url() %}{{ base_url }}?q={{ q|urlencode }}{% if selected_ca
tegories %}&amp;categories={{ selected_categories|join(",") | replace(' ','+') }
}{% endif %}{% if pageno > 1 %}&amp;pageno={{ pageno }}{% endif %}{% if time_ran
ge %}&amp;time_range={{ time_range }}{% endif %}{% if current_language != 'all'
%}&amp;language={{ current_language }}{% endif %}{% endmacro -%}
  File "C:\Python27\lib\site-packages\searx\templates\oscar\base.html", line 82,
 in top-level template code
    {% block content %}
  File "C:\Python27\lib\site-packages\searx\templates\oscar\results.html", line
43, in block "content"
    {% include get_result_template('oscar', result['template']) %}
  File "C:\Python27\lib\site-packages\flask\templating.py", line 57, in get_sour
ce
    return self._get_source_fast(environment, template)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 85, in _get_sou
rce_fast
    raise TemplateNotFound(template)
TemplateNotFound: result_templates/images.html

```

I'm on windows 7 running through python 2.7

The normal search is fine, when I click on images this error happens.
I already inverted the \ to / to match the last not found output, but no results.

**Comment by kvch** [comment] 2017-11-01 16:07
The problem must be around this area:
```jinja
{% for result in results %}
<div class="result {% if result['template'] %}result-{{ result.template|replace('.html', '') }}{% else %}result-default{% endif %}">
    {% set index = loop.index %}
    {% if result.template %}
        {% include get_result_template('oscar', result['template']) %}
    {% else %}
        {% include 'oscar/result_templates/default.html' %}
    {% endif %}
</div>
{% endfor %}

```

**Comment by fabionar** [comment] 2017-11-10 07:58
@kvch I'm sorry but that isn't very helpful, what file are you talking about? There's no oscar/result_templates/default.html.

**Comment by kvch** [comment] 2017-11-10 16:28
Yes, sorry about that. It was just a note for myself, because I thought that I would took another look on a Windows machine in a few days. Unfortunately, I had no time so far.

**Comment by kvch** [comment] 2017-11-10 16:29
Does it happen in case of video or torrent results, too?

**Comment by pandage-search** [comment] 2018-01-25 21:17
Could this be caused by certain characters in the results? Try "harry potter", for example, it fails every single time, but "harry potter now" does not.

Other queries that fail include "joan rivers" and "rome". Perhaps they have something in common.

**Comment by return42** [comment] 2020-01-03 07:55
I guess this issue is fixed in the meantime.  BTW we do not support installation on MS-Windows, to complicated to expensive.  See also [Buildhosts](https://asciimoo.github.io/searx/admin/buildhosts.html).

**Closed as completed by return42** 2020-01-03 07:55 UTC
Labels: bug
