### ISSUE TITLE
youtube video

### ISSUE THREAD

**Issue by sohel1001** [searx/searx#1626] opened 2019-06-19 15:15 UTC
searx engine not fetching videos from youtube

**Comment by kvch** [comment] 2019-06-24 18:18
Which instance? Can you share the backtrace?

**Comment by sohel1001** [comment] 2019-06-25 17:00
Im using cloned version

**Comment by unixfox** [comment] 2020-09-22 13:19
I'm unable to reproduce the issue in a local Searx instance:

![image](https://user-images.githubusercontent.com/4016501/93887290-31234600-fcef-11ea-8ac6-ca8bbecebb06.png)

I'm closing this issue but feel free to reopen it if you are still encountering the issue. Please also provide the source code of the cloned version so that we can diagnose the problem.

**Closed as completed by unixfox** 2020-09-22 13:19 UTC
Labels: engine, can't reproduce
