### ISSUE TITLE
Saving preferences

### ISSUE THREAD

**Issue by eemantsal** [searx/searx#843] opened 2017-01-27 18:56 UTC
Once one has configured Searx according to his desires, how can that configuration be saved so it survives a cookie purge? For example, Startpage permits to generate an obfuscated URL once one has configured the preferences and save it as a new search plugin in Firefox (I suppose it works the same for other browsers too), so no matter if you have Firefox configured to delete cookies when exiting or use some privacy plugin like "Self-Destructing Cookies" that removes cookies automatically; the next time you do a search with SP it will load the language, interface color, servers' location, filters, etc, you have configured.
I haven't seen anything similar for Searx, following the instructions in the FAQ just installs a standard search plugin with the default values, so I guess it's a feature it still lacks and could be implemented, no?

**Comment by asciimoo** [comment] 2017-01-27 19:36
duplicate of #695

**Closed as completed by asciimoo** 2017-01-27 19:36 UTC

**Comment by eemantsal** [comment] 2017-01-28 15:26
Yes, definitely. Sorry, I hadn't seen it.
