### ISSUE TITLE
Change Wikipedia card language

### ISSUE THREAD

**Issue by Schl1gue** [searx/searx#495] opened 2016-01-16 21:58 UTC
Hey guys !
Is it posible to change de language of date returned by the "wikipedia card" displayed on the right side of Oscar theme.
For exampl, if you look for "Johnny Depp", it shows the Wikipedia data but in english, even if all my parameters are French.

Thanks ;)

**Comment by GreenLunar** [comment] 2016-01-21 07:34
Duplicate of #447

**Closed as completed** 2016-02-05 20:01 UTC
