### ISSUE TITLE
With HTTPS only mode enabled in Firefox settings, the images do not load

### ISSUE THREAD

**Issue by tiotrom** [searx/searx#2422] opened 2020-12-26 16:57 UTC
In Firefox, if you enable HTTPS Only Mode, then Searx images are not displayed. Why is that?

**Comment by unixfox** [comment] 2020-12-26 17:26
Which engine are you using? By default, Searx loads the images from the engine server directly without any proxy so if an engine is only HTTP then the images won't work.
But if you use [morty](https://github.com/asciimoo/morty) then every image will be proxied through the Searx server and in HTTPS if Searx is served through HTTPS.

**Comment by tiotrom** [comment] 2020-12-26 17:50
I am using this engine tromland.org/searx/search  but I tested on others too and most seem to suffer from the same issue

**Comment by unixfox** [comment] 2020-12-26 17:59
When I meant the engine it's the engines enabled in the settings not the searx instance.

I tried on a Searx instance with morty and I can't reproduce this issue because every single images are proxied through HTTPS. Here an example of a Searx instance with morty enabled: https://searx.be

Btw your instance is incorrectly configured with morty because it tries to fetch the images from the domain `45.148.28.239` instead of `tromland.org`. You can see that in the developer tools (F12).

I'm going to close this issue as invalid because Searx can't do much about this issue if the enabled engines aren't using HTTPS. A work is in progress for having less HTTP only engines as possible.

**Closed as completed by unixfox** 2020-12-26 17:59 UTC
Labels: invalid

**Comment by tiotrom** [comment] 2020-12-26 21:44
I understand thank you. We are trying to fix that.
