### ISSUE TITLE
docker arm support

### ISSUE THREAD

**Issue by rafalohaki** [searx/searx#3403] opened 2022-11-03 09:49 UTC
Hello,
Is it possible to add arm support?
I had to build it manually and the only thing i changed was line from docker file.
from `FROM alpine:3.15 `to `FROM arm64v8/alpine`
please add something like `docker pull searx/searx:arm64`

**Comment by unixfox** [comment] 2022-11-03 19:33
Duplicate of https://github.com/searx/searx-docker/issues/27

**Closed as completed by unixfox** 2022-11-03 19:33 UTC
Labels: enhancement
