### ISSUE TITLE
Domain filter

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#429] opened 2015-09-12 14:45 UTC
This issue is related to issue #407 but is more complicated.

I would like to filter unwanted results of certain types of websites; I, for example, am not interested to see results from mostly low-class and mostly satirical websites, such as _Urban Dictionary_ and _Uncyclopedia_, they have absolutely no positive value to me, and they, likely, never will.

**Comment by Cqoicebordel** [comment] 2015-09-12 15:46
My answer to #407 could work here too.
A locally (on the user computer) stored list of notes on previous result could help order/hide some results.

**Comment by GreenLunar** [comment] 2015-09-12 15:51
Yes, client-side list is what I had in mind, but how can client-side list be implemented securely?

**Comment by unixfox** [comment] 2021-02-08 13:57
Duplicate of https://github.com/searx/searx/issues/2001

**Closed as completed by unixfox** 2021-02-08 13:57 UTC
Labels: enhancement, core
