### ISSUE TITLE
Settings YAML structure changing on every new docker build

### ISSUE THREAD

**Issue by short-circuit** [searx/searx#2839] opened 2021-06-07 08:53 UTC
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
1.0.0-151-c5d63a5c

**How did you install Searx?**
Docker Compose (Searx, Morty, Filtron)

**What happened?**
Almost on every new docker container update/build the config file structure changes. Sometimes it is spaces, sometimes colons, sometimes indentations. This is reflected on the setting.yaml.new file and doing a diff is a pain and results 99% into a non working instance which has to be configured again since the settings file is immense.

**How To Reproduce**
Update docker container, new file gets generated

**Expected behavior**
No change whatsoever on file structure of `settings.yaml`. Maybe even commit existing setting to the new file and create a log instead of having to manually diff everything.

**Screenshots & Logs**

**Additional context**

I am not sure if I am doing something wrong here since I can't get the new settings files to work. Having to set up everything again every time there is an update to the settings file feels redundant and not manageable anymore at some point. Is there any way the existing changes can be included into the new generated settings file without having to rewrite everything since it is impossible to diff? 
Thanks in advance for any help

**Comment by unixfox** [comment] 2021-06-07 09:18
Duplicate of https://github.com/searx/searx/issues/1209

**Closed as completed by unixfox** 2021-06-07 09:18 UTC
Labels: bug

**Comment by dalf** [comment] 2021-06-07 10:12
In addition may be https://searx.github.io/searx/admin/settings.html#use-default-settings can help you.
