### ISSUE TITLE
Option for user to hide search in title

### ISSUE THREAD

**Issue by 1337god** [searx/searx#2582] opened 2021-02-17 20:54 UTC
![Title of search](https://cdn.discordapp.com/attachments/776115634941591582/811397556092928000/unknown.png)
A way to make it more private for the user by being able to disable the search result in the title in the page so it doesn't show up, because when they click the link it goes to the home page rather than the search

**Comment by unixfox** [comment] 2021-02-17 21:18
Duplicate of https://github.com/searx/searx/issues/1011#issue-253159335

**Closed as completed by unixfox** 2021-02-17 21:18 UTC
Labels: enhancement
