### ISSUE TITLE
Some engines don't obey chosen language

### ISSUE THREAD

**Issue by geckolinux** [searx/searx#1838] opened 2020-02-09 01:47 UTC
Hi there, I noticed that when enabling Yandex I get russian results mixed in, despite having set English as the language:

![Screenshot_2020-02-08 patagonia - searx](https://user-images.githubusercontent.com/2692138/74094725-ef24f700-4ab3-11ea-97f3-fc82b3dd31b2.png)

And Bing news always returns results only in German:

![Screenshot_2020-02-08 coronavirus - searx](https://user-images.githubusercontent.com/2692138/74094735-1aa7e180-4ab4-11ea-81e7-67b9ddea3cef.png)

**Comment by tbergeron** [comment] 2020-02-25 14:12
I'm wondering the same! I use a German hosted mirror and all news content is in German except for Faroo's content. Anyone has an idea of a workaround for that?

**Comment by return42** [comment] 2020-02-25 15:17
Yando and faroo do not support do languages.  To see which engine support languages take a look at the preferences / Engines / column "Selected language"

**Comment by tbergeron** [comment] 2020-02-25 15:18
@return42 I'm talking about Google, Bing, etc. i.e. http://0x0.st/iqDv.png

**Comment by tbergeron** [comment] 2020-02-25 15:21
@return42 both google and bing supports "selected language" http://0x0.st/iqD3.png

so this issue is valid.

This happens because the mirror we use is hosted in another country so when fetching results from Google, Google thinks we're from that country. So when Searx sends a request to Google or Bing it should specify the language it wants results for. (I'll dig up the code to see if I can PR anything)

**Comment by geckolinux** [comment] 2020-02-25 15:32
I agree that this issue is indeed valid, because Bing is supposed to support language filtering, and it frequently contaminates SearX results with wrong-language (mostly German) results.

**Comment by return42** [comment] 2020-02-25 15:38
Sorry, I can't reproduce it .. e.g. my host is located in germany  and when I test google with English selected  

 - [:en !go patagonia](http://darmarit.cloud/searx/?q=%3Aen%20%21go%20patagonia&categories=none&language=en)

I got only english results, if I test with german lang selected, I get only german results from google:

  - [:de !go patagonia](http://darmarit.cloud/searx/?q=%3Ade%20%21go%20patagonia&categories=none&language=de)

bing seems also work

  - [:en !bi patagonia](http://darmarit.cloud/searx/?q=%3Aen%20%21bi%20patagonia&categories=none&language=en)

If you think I am wrong, ask for reopen the issue and give an example at hand / Thanks!

**Comment by return42** [comment] 2020-02-25 15:43
BTW: please use [searx's search syntax](https://asciimoo.github.io/searx/user/search_syntax.html) to test explicit combinations of languages and engines .. no need to activate the search engine in the preferences.

**Comment by tbergeron** [comment] 2020-02-25 15:43
That's the funny thing. Even on my side when using `:en patagonia` in "News" it works. If I do `patagonia` I get German results. This should let you replicate this issue.

And it bugs only when using POST!!! Just noticed this! I switched to GET to send you test URLs and both works :-/ 

So please try to do this:
- Use English & POST in Preferences
- Click on the News tab and search for `:en patagonia`: you won't see German results
- Then on the same News tab search for `patagonia` and you should see German results even if English is selected 

i.e. with GET: http://0x0.st/iqDk.png
with POST: http://0x0.st/iqDn.png

EDIT: Make sure to run the search / refresh a few times after swapping settings.

**Comment by tbergeron** [comment] 2020-02-25 15:43
So the language parameter doesn't seem to be passed to the engine when using POST. Only when using GET for some reason.

**Comment by tbergeron** [comment] 2020-02-25 15:46
Nevermind, even when using GET after refreshing a few times to see more results Google and Bing are still in German... http://0x0.st/iqD7.png

Bonus fun fact: when using the language drop down on the search page. Switching to French actually display French results from Bing and Google XD but switching back to English shows German results.

**Comment by return42** [comment] 2020-02-25 15:49
Please do not mix bing and bing-news engines .. use search syntax and give me an example .. screenshot are not useful for debugging ;).  I also can not see different POST/GET results on my engine .. BTW we made some bugfix on language support these days / did you updated your instance?

**Comment by tbergeron** [comment] 2020-02-25 15:54
I understand. I'm still a bit new using Searx so I'm figuring out the UX and everything at once so thanks for your patience :P I wasn't aware of Searx having separate engines for search/news.

This issue seems to be only happening with Google News and Bing News engine after double checking "general" results. So I now know a bit more of where to focus to debug this issue.

This is not my instance so I cannot alter anything on it unfortunately. It's running on 0.16.0 so maybe it's not totally up-to-date? Do you see anything weird with these settings: http://0x0.st/iqDC.png

I'll do my best to come up with fully 100% reproducible steps. At least now I know it's related only with Bing News and Google News engines.

**Comment by return42** [comment] 2020-02-25 15:59
> I understand. I'm still a bit new using Searx

welcome  :)

I can't speak for other instances. . if unsure use my [instance](https://darmarit.cloud/searx) and give me an example at hand with search syntax .. if you find a different result in GET/POST name  it, so I can reproduce the misbehaviour / thanks!

**Comment by tbergeron** [comment] 2020-02-25 16:03
> welcome :)

thanks a lot :D

First thing when trying your instance: I clicked on News, searched for Coronavirus and behold! German results! http://0x0.st/iqkK.png (after the digg results; yes I know... another screenshot XD)

I'll do my best to hunt down that bug but it is definitively reproducible everywhere I tried damn it :P I see there has been language-related changes in engines on Jan 7 (https://github.com/asciimoo/searx/commit/b63d645a52d663036b97e31a59818d79faa4da81) but I doubt this is the reason why this happens... let's get my hands dirty! hehe

Thanks again for your warm welcome and help!

**Comment by return42** [comment] 2020-02-25 16:13
The changes I told are from the last days ... https://github.com/asciimoo/searx/pull/1860 should be related to the behaviour.   

> Thanks again for your warm welcome and help!

No problem .. but .. please give me a search syntax ;)

**Comment by geckolinux** [comment] 2020-02-25 16:44
- search.disroot.org/?q=coronavirus&time_range=&language=en&category_news=on
   - Some Dutch results mixed in when enabling Bing, this instance is located in Holland.
- searx.info/?q=coronavirus&time_range=&language=en&category_news=on
   - All German results, instance located in Germany

**Comment by return42** [comment] 2020-02-25 17:23
**Again, no need to switch to a category, no need to enable a engine in the preferences** .. to see misbehaviour of a engine select this engine explicit with search syntax.

Anyway I see a that bing-news brings german results on top for servers hosted in germany, even if we select the english language ... same with google-news

- [:en !bin coronavirus](http://darmarit.cloud/searx/?q=%3Aen%20%21bin%20coronavirus&categories=none&language=en)

- [:en !gon coronavirus](http://darmarit.cloud/searx/?q=%3Aen%20%21gon%20coronavirus&categories=none&language=en)

For now the only thing I can say, that (some) news-engines do not support languages .. I will have a look on bing-news and google-news.

**Comment by tbergeron** [comment] 2020-02-25 17:45
> **Again, no need to switch to a category, no need to enable a engine in the preferences** .. to see misbehaviour of a engine select this engine explicit with search syntax.

Good to know even if it's disabled in preferences, we can still use the shortcuts. I wasn't aware of that. Sorry for not being able to come up with search syntax right away. I now understand better the concept. Thanks for your patience with us, I forked the code and will play around to learn the development environment and might start to contribute soon. I really love the project, great idea and great execution! Keep up the great work!

**Comment by tbergeron** [comment] 2020-02-25 18:16
@return42 just saw the commit already passing through, you are a mad man! thanks so much for already figuring this out for us! How does releases work? I guess this change will be available on your instance sooner than any other since I guess admins need to update manually their instances? Sorry for throwing so many questions at you 😆

**Comment by return42** [comment] 2020-02-25 18:28
>  I guess this change will be available on your instance sooner than any other

First the PR needs reviewed & merged .. 

> I guess admins need to update manually their instances?

We recommend to [update from git repos](https://asciimoo.github.io/searx/admin/installation.html?highlight=update#how-to-update)

See also my remark why versioning does not make much sense / [engines are a moving targets, this issue is the best example](https://github.com/asciimoo/searx/issues/1792#issuecomment-570203111)

**Comment by return42** [comment] 2020-02-25 18:29
@geckolinux @tbergeron 

If you find more engines not working please open new issue with the search syntax selecting explicite the engine and language and we can react much faster ;)

Another tip: it is very easy to test a up-to-date instance locally (in your download folder where you can delete it after your tests)

    $ cd ~/Download
    $ git clone https://github.com/asciimoo/searx/
    $ cd searx
    $ make run

**Comment by geckolinux** [comment] 2020-02-25 19:17
@return42 Hey, cool, I didn't know it was that easy to test it. I just did as suggested.

So I'm still seeing that with Bing _and_ Google news engines, it's giving me local results in a non-English language, despite me having specified English.

**Comment by return42** [comment] 2020-02-25 19:26
The PR #1866 is not yet merged .. if you want to merge the PR locally just pull it:

    git pull origin refs/pull/1866/head

 .. if started, first stop `make run` with `[CTRL-C]` ..

**Comment by geckolinux** [comment] 2020-02-25 19:35
On 25/2/20 14:26, Markus Heiser wrote:
> The PR #1866 <https://github.com/asciimoo/searx/pull/1866> is not yet merged 

Oops, sorry. I applied your fixes now. Google News results are now in English as specified, but Bing News results are all still in the regional language.

**Comment by tbergeron** [comment] 2020-02-25 20:18
Very nice to know it's so easy to test and start hacking away on it! I never thought I'd be able to play around with my own locally ran search meta engine :D Pretty cool!

I've been using Searx for the whole day for my development work and the !it tab is MIRACULOUS. Great results, it's amazing to be able to hand pick the engines we want. Love it!

**Comment by return42** [comment] 2020-02-26 04:45
> but Bing News results are all still in the regional language.

Yes I see .. sorry, I have to look deeper.

>  Very nice to know it's so easy to test and start hacking away on it! 

Thanks! ["mission complete"](https://asciimoo.github.io/searx/dev/contribution_guide.html?highlight=hackability)

**Comment by return42** [comment] 2020-03-01 10:14
@tbergeron @geckolinux 

The bing_news bug was caused by wrong language tags, which is fixed by patch e0c99d9d and 7941282  in this PR. Can you pull the PR again and retry? / Thanks

**Closed as completed** 2020-03-04 11:00 UTC

**Comment by return42** [comment] 2020-03-04 12:37
@tbergeron @geckolinux FYI: the patch is merged, I also updated my instance https://darmarit.cloud/searx/

**Comment by tbergeron** [comment] 2020-03-04 19:52
@return42 awesome! works perfectly both on your instance and my private instance :D thx a lot! searx is PERFECT! Even picking a more specific language like en-CA instead of en shows more Canadian english content. I definitively see a difference now that it's fixed :D
