### ISSUE TITLE
No search results with Google engine 'allowed,' "Rate Limit Exceeded" with it not allowed.

### ISSUE THREAD

**Issue by snurfle** [searx/searx#1731] opened 2019-10-25 13:10 UTC
I tried searx.me about 6 months ago, and never received any results to any search. I gave up and went on; there's a lot of places to search.
Tried again today just as a lark, and still don't receive any results regardless of what I search for.
The comments on here are a little... random... rather than actual solutions, but I was able to find a few places where people said that Google just needs shut off in the search engines as it no longer works with searx (so why is it still even an option? and why is it enabled by default?!?!)
Turning google off only takes me to a white page with black text: "Rate limit exceeded"
Turning google on only returns " Error! Engines cannot retrieve results." and tells me to "Please, try again later or find another searx instance."
What is another "instance?" A different web page to search from? I don't understand that statement.
I also don't understand why a web site that purports to give search results and privacy is still active if it returns nothing at all.  Obviously I am doing something wrong by just entering a word and clicking on the little magnifying glass.  What are the correct steps to use this web site?

**Comment by return42** [comment] 2019-11-23 08:55
Should be obsolete with #1748 and PR #1749.

**Comment by return42** [comment] 2019-12-06 13:57
Update: old google UI is dead https://github.com/asciimoo/searx/issues/1748#issuecomment-562549293 / lets close this issue and continue at issue https://github.com/asciimoo/searx/issues/729 / thanks!

**Comment by unixfox** [comment] 2019-12-10 10:17
@return42 duplicate of #729, this issue can be closed.

**Closed as completed** 2019-12-10 10:51 UTC
