### ISSUE TITLE
[Feature Request] Please let us make searx the default search engine with Chrome/Chromium browsers and Android operating systems.

### ISSUE THREAD

**Issue by bat999** [searx/searx#1885] opened 2020-03-06 19:49 UTC
Hi
I use Chromium v80 browser with an Android Oreo v8.1.0 operating system phone.

There is a method known as "OpenSearch".
The documentation is here...
https://developer.mozilla.org/en-US/docs/Web/OpenSearch

With OpenSearch the webpage has some extra code.
It tells the browser "Hey, I am a search engine".
With that knowledge we can add it as a default search engine for future use.

This seems to work OK with some search engines.
For example...
https://ecosia.org/
https://lite.qwant.com/
https://yandex.com/

But it won't work for me with... 
https://searx.be/

Can you please fix it so that searx instances handle OpenSearch properly with Chrome/Chromium browsers and Android operating systems. 

Here is a demonstration...
1
Go to the Qwant Lite website at https://lite.qwant.com/
2
Perform a search.
3
Look in Chrome/Chromium Menu > Settings > Search Engine.
4
See that Qwant Lite is shown as "Recently Visited".
5
Make Qwant Lite the default search engine.

![demonstration](https://user-images.githubusercontent.com/640761/76117112-18697200-5fe3-11ea-8435-da39c20e6186.jpg)

**Comment by unixfox** [comment] 2020-03-06 20:35
Duplicate of https://github.com/asciimoo/searx/issues/1666

**Closed as completed** 2020-03-06 20:40 UTC
