### ISSUE TITLE
[Feature Request] Please make Oscar theme less cluttered on small-screen devices.

### ISSUE THREAD

**Issue by bat999** [searx/searx#2136] opened 2020-08-10 22:22 UTC
Hi
With Simple theme the "Links" are hidden for small-screen devices.

Oscar is a better theme.
Can the "Links" be hidden for small-screen devices with Oscar theme also?

The "Suggestions" take up a lot of space.
Perhaps they could be hidden too for small-screen devices with Oscar theme. 
I think that "Suggestions" are generated by the Google engine, maybe others too.

![links_and_sugg](https://user-images.githubusercontent.com/640761/89837058-0eced200-db60-11ea-82dc-754d2619b53f.jpg)

**Comment by MarcAbonce** [comment] 2020-08-11 06:20
Same issue as #2086.
Relevant discussion in #1781.

**Comment by dalf** [comment] 2020-08-11 06:52
I close this issue it is a duplicate of #2086 

> Oscar is a better theme.

Out of curiosity, how the oscar theme is better ?

**Closed as completed by dalf** 2020-08-11 06:52 UTC
Labels: duplicate, ui / ux

**Comment by bat999** [comment] 2020-08-11 09:17
> 
> Out of curiosity, how the oscar theme is better ?

On (my) small-screen device with Simple theme "Preferences" window does not show on home page or results page.
(With Desktop it is there in top right hand corner)

With Simple theme "Infinite Scroll" doesn't seem to work with either small-screen or Desktop.

**Comment by dalf** [comment] 2020-08-11 14:15
@bat999 thank you for the feedback.

The two issues are recorded in this meta-issue: https://github.com/asciimoo/searx/issues/1025
> On mobile: make the search input smaller when without focus to give space for the searx logo and the preferences button. With focus, make it full width wide as now.
> General : UX: infinite_scroll plugin
