### ISSUE TITLE
Persistent Preferences

### ISSUE THREAD

**Issue by DrrAld** [searx/searx#1810] opened 2020-01-23 15:27 UTC
Hello. Hopefully someone can help clear this up.

I’m using a fresh, local install of searx with Firefox 72 (the latest) and having a hard time getting saved preferences to stick. 

For testing: I’ve entered the url found on bottom of the preferences page in the address bar and saved searx as an engine from that instance. When I close Firefox, reopen and search, none of my preferences persisted.

I’ve also saved the url as an allowed cookie within Firefox, but the preferences are still not persisting after closing and reopening. I’ve done this with and without clearing cookies and both instances resulted in the same state; searx with default preferences and not the saved ones.

Any help is appreciated.

**Comment by Fluffkin** [comment] 2020-03-05 01:39
Not sure if it's related because I'm trying to get cookies to stick on a local searx instance. In this case Waterfox 2020.02. Every once in a while the cookies seem to reset to defaults. All the cookies are still there saved by the browser, but none of the preferences are saved.

I was about to try the url method then found your issue saying that somehow breaks as well.
[Edit for typo]

**Comment by Fluffkin** [comment] 2020-03-22 22:20
I might be able to help a little now I've dug in to it. You need to add the custom url to Firefox using a custom search engine addon like this one: https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/ 

But it doesn't help as much as you might hope. For example if I use it for a general search, then click "News" to try a news search on the same term, all the preferences in the url are ignored.

Meanwhile if I try depending on cookies alone, Searx still seems to randomly reset them. Sometimes a couple of times a day, sometimes not for 2 or 3 days. I'm not aware of my browser forgetting cookies from any other websites I use. It's only Searx that has the problem.

I'm a bit puzzled why nobody else is reporting this problem though.

**Comment by DrrAld** [comment] 2020-03-23 09:23
> Not sure if it's related because I'm trying to get cookies to stick on a local searx instance. In this case Waterfox 2020.02. Every once in a while the cookies seem to reset to defaults. All the cookies are still there saved by the browser, but none of the preferences are saved.
> 
> I was about to try the url method then found your issue saying that somehow breaks as well.
> [Edit for typo]

I ended up hardcoding my preferences in preferences.py. No issue thus far.

**Comment by unixfox** [comment] 2020-12-28 19:08
I've used my instance (https://searx.be) without touching my previously configured preferences for almost one year now, and I never got any preferences reset in that whole year.
I'm closing this issue because I just cannot reproduce this issue at all, and it's probably due to a misconfiguration from your end on your Searx instance or due to a plugin messing with the cookies.

If you still experience this issue then please paste a lot of information that could help us replicate the issue: Searx instance URL, browser used, extensions installed and more.

**Closed as completed by unixfox** 2020-12-28 19:08 UTC
Labels: can't reproduce
