### ISSUE TITLE
[Engine] Unsplash.com - Image search

### ISSUE THREAD

**Issue by ghost** [searx/searx#1340] opened 2018-07-02 18:46 UTC
This is a great source of no strings attached quality photographs. They have a huge collection and there's no restrictions on them (free for personal or for profit). All they ask is that, if you desire, credit be given to the photographer.

https://unsplash.com/developers
https://unsplash.com

**Comment by dadosch** [comment] 2018-08-18 02:29
https://unsplash.com/search/photos

**Parameters**
`query` 	Search terms.
`page`	Page number to retrieve. (Optional; default: 1)
`per_page` 	Number of items per page. (Optional; default: 10)
`collections` 	Collection ID(‘s) to narrow search. If multiple, comma-separated.
`orientation` 	Filter search results by photo orientation. Valid values are landscape, portrait, and squarish.


From: https://unsplash.com/documentation#search-photos

**Comment by Venca24** [comment] 2019-05-23 11:33
Actually implemented in PR #1412

**Comment by allendema** [comment] 2021-05-25 17:18
Could be closed as the issue is solved.

**Closed as completed** 2021-06-21 13:12 UTC
Labels: engine request
