### ISSUE TITLE
Implement reverse image search

### ISSUE THREAD

**Issue by romulasry** [searx/searx#2002] opened 2020-06-16 00:07 UTC
Good idea?

**Comment by unixfox** [comment] 2020-06-16 08:30
How would you integrate that in Searx? I'm not talking about the code but from the interface perspective (the website).

**Comment by return42** [comment] 2020-06-16 08:46
A upload button in the "images" category?

**Comment by SuperSandro2000** [comment] 2020-06-16 09:51
I don't think this is possible in a privacy focused way cause we would need to upload the picture to every search that supports it.

**Comment by return42** [comment] 2020-06-16 10:04
I understand your concern, but isn't it the same with every search term which is send upstream to the search engines?

**Comment by SuperSandro2000** [comment] 2020-06-16 10:21
Pictures are more unique and can contain exif data which can leak quite a bit of information. Search terms usually contain a lot less information especially if you are searching for something short and generic like github.

**Comment by return42** [comment] 2020-06-16 10:29
> and can contain exif data which can leak quite a bit of information

Good point!

**Comment by dalf** [comment] 2020-06-16 10:34
Duplicate of https://github.com/asciimoo/searx/issues/1895
But the given user case reverse searches an existing public URL. In this is case there is no privacy  concern about the EXIF data.

**Comment by return42** [comment] 2020-06-16 10:54
Another good point: Searching images similar to an already public image might be a use case. But I can already hear the users asking for a upload button :)

**Comment by romulasry** [comment] 2020-06-16 17:22
You could remove the EXIF data by default.

**Comment by asciimoo** [comment] 2020-07-27 13:27
Image upload raises quite a few questions and makes the implementation much more complicated. I agree with @dalf , allow only the use of already uploaded images URLs. In this case these services can be added as new engines and the integration would be seamless. Lets continue this discussion in #1895 .

**Closed as completed by asciimoo** 2020-07-27 13:27 UTC
Labels: enhancement
