### ISSUE TITLE
exclude subdomains

### ISSUE THREAD

**Issue by ilf** [searx/searx#375] opened 2015-06-23 19:12 UTC
I would like to search within a site:domain.tld, but exclude results from all its subdomains.domain.tld. Is this possible?

Like https://searx.me/?q=site%3Agoogle.com+!site%3A*.google.com - but that shows results from www.google.com, news.google.com and others.

**Comment by dalf** [comment] 2015-06-24 12:55
For now, searx doesn't parse the request (except the bangs and language selection). In others words, if google allows a such thing, it is possible to have the same result in searx.

But, regarding the `!site:` it is possible to something since searx can filter the result according this filter. A naive implementation would possibly give zero result on the first page but some on the next page.

**Comment by unixfox** [comment] 2021-01-04 15:48
Duplicate of https://github.com/searx/searx/issues/1008

**Closed as completed** 2021-01-04 15:55 UTC
Labels: enhancement, question
