### ISSUE TITLE
Change default search preferences to minimize pornographic images

### ISSUE THREAD

**Issue by sorenstoutner** [searx/searx#1433] opened 2018-11-06 22:02 UTC
I am the developer of the [Privacy Browser](https://www.stoutner.com/privacy-browser/). Recently I switched the default homepage and search engine from [DuckDuckGo to Searx.me](https://www.stoutner.com/new-default-homepage-and-search-engine/). Since doing so, the only complaint I have received has been that Searx with default settings returns pornographic images for almost any search term.

I have created instructions for users to change the [default preferences](https://www.stoutner.com/privacy-browser/common-settings/searx/). But the premise behind Privacy Browser is to browse with cookies disabled and to wipe any that are created every time the program closes. Maintaining a cookie to set these preferences breaks that model.

My recommendation is that Searx's default image settings disable any source that does not support SafeSearch and that SafeSearch be set to Moderate or Strict. Note that I am not recommending that options for finding porn be removed from Searx for those that want to use them. Rather, I am recommending that the Searx defaults be considerate of those who do not want to accidentally be exposed to porn.

**Comment by sorenstoutner** [comment] 2019-02-13 05:33
The 0.15.0 release seems to have improved the state a bit, with terms like "test" no longer pulling up hard core pornography on the first page.  But there is still room for improvements in the default settings.

**Comment by bourrel** [comment] 2019-02-13 10:06
Maybe you should create your own instance of searx and set the default level of SafeSearch to strict in the preferences

**Comment by sorenstoutner** [comment] 2019-02-13 17:51
I have though a lot about that and will likely do so at some point in the future, but it isn't an option for me in the short term.  Are you aware of any public instance that has safe image search by default?

**Comment by bourrel** [comment] 2019-02-15 10:42
Unfortunately I don't know any public instance that has safe image search by default but you could check this list of instance : https://github.com/asciimoo/searx/wiki/Searx-instances

**Comment by jfowl** [comment] 2019-02-15 16:38
@sorenstoutner

I see two rather _easy_, but whacky solutions:

1. Saving the safe-search preference into the search-url
![image](https://user-images.githubusercontent.com/15788906/52870231-41e8fe80-313f-11e9-8a5d-4f6bd0eb1e7e.png)

2. Overriding cookies for searx.me by *you*:
![image](https://user-images.githubusercontent.com/15788906/52870294-6e047f80-313f-11e9-9f87-0754da34762b.png)
That way, your users must not do that on their own.

Both of them can be found here: https://searx.me/preferences.

What are your requirements for a privacybrowser searx-instance?
Would you be willing to add a DNS CNAME/A entry of search.stoutner.com for that?

**Comment by sorenstoutner** [comment] 2019-02-15 18:38
> I see two rather _easy_, but whacky solutions:
> 
>     1. Saving the safe-search preference into the search-url
>        ![image](https://user-images.githubusercontent.com/15788906/52870231-41e8fe80-313f-11e9-8a5d-4f6bd0eb1e7e.png)

I have played around with saving preferences quite a bit.  But it can't accomplish what I need for two reasons.

1.  It doesn't work correctly (perhaps I ought to file a separate bug about this).  If I use the custom URL to load a page or perform a search, it does so correctly.  But the first time I click on any link that leads to another part of the searx.me website, the preference string is stripped from the URL and the default settings are loaded.  So, for example, if I use the custom URL without the `?q=` at the end as a homepage, as soon as I do a search using the search box on the screen the custom preferences are stripped out and I get a search with the default settings.  If I use the URL with the `?q=` as a search query, the results under General use the saved preferences, but as soon as I switch it to Images the saved preferences are stripped out and a search is performed using the default settings.

2.  Even if the problems described in number 1 were resolved, using custom preferences doesn't work well for my purposes.  If I set a custom URL as the default in Privacy Browser, than any user can edit those settings and they would apply to everyone else who uses the browser.  If I include instructions for users to create their own custom URL then whoever is hosting the Searx instance can track individual users over time.  That is exactly the sort of tracking I am trying to avoid.

>     2. Overriding cookies for searx.me by _you_:
>        ![image](https://user-images.githubusercontent.com/15788906/52870294-6e047f80-313f-11e9-9f87-0754da34762b.png)
>        That way, your users must not do that on their own.

I do not currently have the ability to allow some cookies and disallow others for a particular domain, nor do I have the infrastructure in place to inject a specific cookie for a particular website.  Although that will be possible in a future release with the 4.x series of Privacy Browser, that will involve forking Android's WebView to create [Privacy WebView,](https://redmine.stoutner.com/issues/86) and isn't a good solution for the short term.

> Both of them can be found here: https://searx.me/preferences.
> 
> What are your requirements for a privacybrowser searx-instance?
> Would you be willing to add a DNS CNAME/A entry of search.stoutner.com for that?

I can easily add a CNAME/A entry for search.stoutner.com that points to a Searx instance that has these as default settings.  I am just not in a position to host one myself right now.  Going forward, I intend to host my own instance and likely contribute to the project.  But even when I do, I assume that there are a number of people, besides just those who use Privacy Browser, who would like an easy URL to safely search images.  Something like safesearch.searx.me or safe.searx.me or clean.searx.me would be a nice addition to the standard build.

**Comment by jfowl** [comment] 2019-02-18 19:28
Just as a note for future me: nginx-Cookie-Injection.
- Run a single searx instance
- nginx injects cookies based on subdomain (e.g. safe.searx.tld, dark.searx.tld, ...)

**Comment by n-o-o-b** [comment] 2019-03-20 00:36
SafeSearch should be set to Moderate by default
would be nice to not have to see heads with holes blown through them when searching for something

**Comment by esmoak** [comment] 2019-04-07 15:41
I'm not sure if it helps much, but this instance defaults to "moderate."

https://searxes.danwin1210.me/

It is the meta one listed as Danwin.
https://github.com/asciimoo/searx/wiki/Searx-instances

**Comment by unixfox** [comment] 2021-01-04 15:05
Duplicate of https://github.com/searx/searx/issues/1410

**Closed as completed by unixfox** 2021-01-04 15:05 UTC
