### ISSUE TITLE
A way to make it easy to generate Other Search Indexes Like including google CSE or something

### ISSUE THREAD

**Issue by JoshWho** [searx/searx#3340] opened 2022-08-12 05:15 UTC
I want to be able to search custom websites like JoshWho TV and Bitchute for videos but I do not see anything about that. Is there a way to include a custom google search engine to my instance?

I can't seem to find any way for this.

**Comment by JoshWho** [comment] 2022-08-12 05:58
Just a basic temple example to help me get started.

So far this is what I have found

```
"""
 JoshWho-Search
"""

# about
about = {
    "website": JoshWho Search,
    "wikidata_id": None,
    "official_api_documentation": None,
    "use_official_api": False,
    "require_api_key": False,
    "results": 'empty array',
}


# engine dependent config
categories = ['general']
paging = True

# search-url
base_url = 'https://cse.google.com/cse?cx=012551626225644270009:mq2cfvxhkg4#gsc.tab=0'
search_string = '&gsc.q=fart&gsc.sort={page}'

# do search-request
def request(query, params):
    search_path = search_string.format(
        query=urlencode({'q': query}),
        page=params['pageno'])

    params['url'] = base_url + search_path

    return params
```

Is there anything else I need for this to work?

**Comment by unixfox** [comment] 2022-08-12 06:35
Enable only google engine and just type `site:thedomain.com yoursearchquery`.
More info: https://support.google.com/websearch/answer/2466433?hl=en

Duplicate of https://github.com/searx/searx/issues/2952

**Closed as completed by unixfox** 2022-08-12 06:35 UTC
Labels: enhancement

**Comment by JoshWho** [comment] 2022-08-12 08:14
> Enable only google engine and just type `site:thedomain.com yoursearchquery`. More info: https://support.google.com/websearch/answer/2466433?hl=en
> 
> Duplicate of #2952

Thank you will give it a try soon

**Comment by JoshWho** [comment] 2022-08-12 08:15
> > Enable only google engine and just type `site:thedomain.com yoursearchquery`. More info: https://support.google.com/websearch/answer/2466433?hl=en
> > Duplicate of #2952
> 
> Thank you will give it a try soon

Now will this let me use the cse? Im not understanding the duplicate thing?  This is not referencing what you linked to.

I do not want the other engines disabled I just want this included in the general findings

**Comment by unixfox** [comment] 2022-08-12 08:41
Google CSE is just the feature `site:` on steroids, it's the same functionality.

I wrote `duplicate` because google cse is like a search box for searching for things for a specific website and we already have an issue opened for that.
