### ISSUE TITLE
duckduckgo: the language preference is sometime ignored

### ISSUE THREAD

**Issue by dalf** [searx/searx#2259] opened 2020-10-10 08:47 UTC
The duckduckgo engine has been updated: #2254

But the language support still have a problem: it works if there is no more than one request per minute, otherwise it is ignored (it seems to pick the Russian language ?)

But it seems to work with curl:
```sh
curl --http1.1 'https://html.duckduckgo.com/html/' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0' --data-raw 'q=test&b=&kl=fr-fr&df=' | grep "leconjugueur.lefigaro.fr"
```

 so most probably I'm missing something ?

https://github.com/searx/searx/blob/e78bfd4d8b62a521e08029bb0e708b2bcec9958d/searx/engines/duckduckgo.py#L53-L82

**Comment by CaffeinatedTech** [comment] 2020-12-10 04:30
I'm seeing so many Russian results lately.  It's almost unusable.

**Comment by MarcAbonce** [comment] 2020-12-10 08:18
I was able to reproduce this with curl:
`curl --http1.1 'https://html.duckduckgo.com/html/' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0' --data-raw 'q=beatles&b=&kl=fr-fr&df=' | grep "и"`
I get Russian results the second time.

Strangely enough, I could even reproduce this bug directly with the UI in https://html.duckduckgo.com/html.

**Comment by dalf** [comment] 2020-12-10 08:33
> Strangely enough, I could even reproduce this bug directly with the UI in https://html.duckduckgo.com/html.

I have seen that `https://duckduckgo.com/t/sl_h` is blocked by ublock origin, so here a patch that call this URL with the same headers, it seems better, but I can't confirm.

```patch
diff --git a/searx/engines/duckduckgo.py b/searx/engines/duckduckgo.py
index c1c98462..58c361de 100644
--- a/searx/engines/duckduckgo.py
+++ b/searx/engines/duckduckgo.py
@@ -15,7 +15,8 @@
 
 from lxml.html import fromstring
 from json import loads
-from searx.utils import extract_text, match_language, eval_xpath
+from searx.utils import extract_text, match_language, eval_xpath, dict_subset
+from searx.poolrequests import get
 
 # engine dependent config
 categories = ['general']
@@ -36,6 +37,7 @@ language_aliases = {
 
 # search-url
 url = 'https://html.duckduckgo.com/html'
+url_ping = 'https://duckduckgo.com/t/sl_h'
 time_range_dict = {'day': 'd',
                    'week': 'w',
                    'month': 'm'}
@@ -84,6 +86,10 @@ def request(query, params):
 def response(resp):
     results = []
 
+    # ping
+    headers_ping = dict_subset(resp.request.headers, ['User-Agent', 'Accept-Encoding', 'Accept', 'Cookie'])
+    get(url_ping, headers=headers_ping)
+
     doc = fromstring(resp.text)
 
     # parse results
```

**Comment by MarcAbonce** [comment] 2021-01-10 05:10
I forgot to comment here but yeah, that code worked for me.

Technically we shouldn't have to ping that URL every single time because duckduckgo seems to remember each IP+User-Agent for over an hour at least, but for that we would have to keep track of those pings, similar to [wolframalpha_noapi.py](https://github.com/searx/searx/blob/master/searx/engines/wolframalpha_noapi.py) but for every IP+User-Agent combination (in case an instance is using a proxy pool).

So, I think your solution would be the best for now.

**Comment by return42** [comment] 2021-01-10 08:30
The behavior is not completely clear to me.  When I use DDG directly (https://html.duckduckgo.com/) searching the term 'foobar', first I got a _long_ list of results.  If I repeat this request again I get only a few results.

What I mean: the symptoms are not limited to russian results.  But disabling uBlock seems to solve this problem.

With the patch from @dalf applied, the issue seems to be solved, I always get a _long_ result list.

I would vote to merge the patch from @dalf into master branch.

**Comment by dalf** [comment] 2021-01-10 10:32
Note the patch won't work when searx is configured with different IP or proxies : the two request will most probably use two different IP (or proxies).

`searx.poolrequests` and / or `searx.search` must provide a dedicated HTTP client the time the engine run.

Perhaps it can be done using a threading.local (untested code):
https://github.com/searx/searx/blob/c2646df496565bbf66ecfa6baf9cedee1de416cf/searx/poolrequests.py#L70

So instead of 
https://github.com/searx/searx/blob/c2646df496565bbf66ecfa6baf9cedee1de416cf/searx/poolrequests.py#L146

we can have:
```python
if 'session' in threadLocal.__dict__:
  session = threadLocal.__dict__['session']
else:
  session = SessionSinglePool() 
  threadLocal.__dict__['session'] = session
```

**Comment by return42** [comment] 2021-03-25 13:42
I tested this issue with #2560 merged .. for me the results are much better than before (ping seems to help) .. ddg results have it quirks, but I don't think that theses are related to this issue / I recommend to close this issue.

**Closed as completed** 2021-03-25 13:53 UTC
Labels: bug, engine
