### ISSUE TITLE
Trouble with Qwant

### ISSUE THREAD

**Issue by GGBoCa** [searx/searx#1300] opened 2018-05-16 12:39 UTC
Hey,

I don't know to much about coding but I'm interested in privacy and Searx is a great tool... So thanks to people who work on it.

I try many instances of Searx : searx.me, searx.prvcy.eu then searx.elukerio.org and I always have the same problem with qwant. It works at the beginning (only in the morning I guess) and it doesn't work anymore. There is no wrong message like for Gigablast : 
"Engines cannot retrieve results:
gigablast (unexpected crash: No JSON object could be decoded)"

There is no  I try to change every parameters one by one (languages, POST or GET, skin...). Nothing change.

Do you have an idea to fix that ? Or for Gigablast maybe ?

Thanks anyway.
Keep fighting

GG

... and excuse my french.

**Comment by kvch** [comment] 2018-05-16 21:16
What was your query? I tried reproducing the error with multiple queries on the instances you mentioned and also on mine and locally. But I wasn't successful.

**Comment by GGBoCa** [comment] 2018-05-17 12:58
Hey, thanks for reading and take a minute to help. To tell it simply Qwant doesn't work (qw normal, actuality, image or whatever). It's weird because if I try a new instance it works well, once, twice, then... it doesn't anymore. And sometimes (something like once a week) it works for one search. And I can't explain this myself. Unfortunately, I don't have too much informations to help. I use Firefox with many privacy addons, a VPN but qwant is the only instance (I tried) which doesn't work without telling there is a problem (like Gigablast and json stuff...).
Sorry to not be very very understandable...

**Comment by GGBoCa** [comment] 2018-05-18 14:08
I checked today. It qwant works between "around" 11am and 2pm (french time).

**Comment by kvch** [comment] 2018-05-21 13:58
I tried again today, even from behind a proxy, but it works every time both a local instance and https://searx.kvch.me What is the error message you get for qwant?

**Comment by GGBoCa** [comment] 2018-05-21 14:05
It use to work for this morning. Yesterday it doesn't. 

There is not error message when it doesn't work. There is simply no result from qwant. As it doesn't exist.

But as I said it's OK today. I'll tell you if the problem is magically fixed on the next days.

Wait and see.
Tschüss

**Comment by GGBoCa** [comment] 2018-05-29 20:00
For the first time ever (in my case), it works for more than one week now.
So the only solution is the problem was solved by writing on this forum. I'll logically tell you if my fridge or my car is out of order.
Thanks
Tschüss

GG

**Comment by elukerio-dev** [comment] 2018-06-29 15:34
Hey @GGBoCa 
we are a french association named [elukerio.org](https://www.elukerio.org) and we maintain [searx.elukerio.org](https://searx.elukerio.org) so we have already seen this problem many times with qwant (qw), it comes from the fact that the ip of our server is regularly banned by qwant due to the large number of requests that our instance. Indeed our instance is one of the most used (more than 2 million requests per month) and especially by French community which likes to use qwant. So the only solution we found is to connect with the VPN of our association to have the same public IP as our instance, then we go to qwant.com, and there the site thinks we are unwanted traffic and shows us a captcha. Then just fill it up, and the qwant engine starts working as before. It's really do-it-yourself but it has the merit to work during 2 weeks, then it's necessary to start again the manipulation. Otherwise we contacted qwant but no answer...

**Comment by GGBoCa** [comment] 2018-06-30 07:08
Salut,

Alors je peux parler français ! Merci pour l’info, cela ne m’étonne pas trop que Qwant ne réponde pas. La collaboration avec le monde du libre n’a pas trop l’air d’être dans le style de la maison.
Dans tous les cas, cela fait plusieurs semaines que cela fonctionne correctement, sans avoir à faire de bidouille donc pour l’instant plus de problème. J’essaierai la technique du VPN si jamais ça ne remarche plus.

Merci encore pour cette réponse personnalisée et pour l’ensemble de votre travail.

So see soon
Christophe
\CH_ocolat_{0041.78.763.28.24}
 \FR_omage_{0033.686.75.80.10}

**Comment by asciimoo** [comment] 2019-12-21 20:17
fixed in 8850036ded3af2ba7455cef53a8134022e1b544d

**Closed as completed by asciimoo** 2019-12-21 20:17 UTC
Labels: engine

**Comment by bqv** [comment] 2020-11-13 15:59
This is an issue again, afaict
