### ISSUE TITLE
Multiple Language Search

### ISSUE THREAD

**Issue by dosch** [searx/searx#1351] opened 2018-07-30 07:38 UTC
As English is dominant on the web, it makes no sense to leave that language out of the search results. But I also want to have localized search result in my own (Dutch) language.

Being able to get results for two languages would be amazing

**Comment by dimqua** [comment] 2018-07-30 11:49
Duplicate of #1344

**Comment by dosch** [comment] 2018-07-30 12:07
@dimqua how is that a duplicate? The referenced issue is a bug. This is a feature request.

**Comment by Pofilo** [comment] 2018-07-30 13:21
@dimqua is right, this is a duplicate of #1344.

Both issues are suggesting to make researches in different languages (native for example Dutch for you + english). It makes a lot of sense but needs to be implemented.

**Closed as completed by Pofilo** 2018-07-30 13:21 UTC
