### ISSUE TITLE
Next page missing from searx v. 0.14.0 (only one page of results)

### ISSUE THREAD

**Issue by beatstick** [searx/searx#1404] opened 2018-09-26 20:50 UTC
I only ever get one page of results since the update to 0.14.0 on my self-hosted searx instance. 
Is this a bug or am I missing some obvious setting? I haven't found anything in the config file.

**Comment by Pofilo** [comment] 2018-09-26 20:57
It depends of your configuration. If you go into the **Preferences** in the plugin section, you have one name **Infinite scroll**. Is it activated ?

**Comment by beatstick** [comment] 2018-09-26 20:59
I tried activating infinite scroll as well. I still only get one page of results. It makes no difference.

**Comment by jordemort** [comment] 2018-10-19 06:03
Seeing the same problem on my instance (0.14, just refreshed my container from master today)

**Comment by Perflyst** [comment] 2020-08-17 17:59
I still have the same issue with v0.16.0 and v0.17.0

**Comment by unixfox** [comment] 2020-12-28 18:45
Please paste the enabled engines in the preferences and if it's possible the URL to the Searx instance used.

Usually this bug is related to an engine that silently fails because the server is rate limited or blocked by the service used.

**Comment by unixfox** [comment] 2021-01-04 13:38
Probably duplicate of https://github.com/searx/searx/issues/2053

**Closed as completed by unixfox** 2021-01-04 13:38 UTC
