### ISSUE TITLE
Engines cannot retrieve results

### ISSUE THREAD

**Issue by ghost** [searx/searx#1868] opened 2020-02-25 18:47 UTC
how can I completely remove the error element from the page: Engines cannot retrieve results

**Comment by fabthegreat** [comment] 2020-03-02 09:48
Have the same issue, often only one page of results displays, and if I click to next, error occurs. I need to reload the search.
Someone has a trick?

**Comment by unixfox** [comment] 2020-12-28 19:13
Duplicate of https://github.com/searx/searx/issues/2053

**Closed as completed by unixfox** 2020-12-28 19:13 UTC
