### ISSUE TITLE
Feature request: Includable sub-settings.yaml files.

### ISSUE THREAD

**Issue by virtadpt** [searx/searx#2780] opened 2021-04-26 17:33 UTC
**Is your feature request related to a problem? Please describe.**
I have a couple of non-standard search engines configured in my personal Searx instances.  This causes problems when updating - I have to manually edit my searx/searx/settings.yml file because stuff gets moved up, down, and elsewhere.  Most recently I had to re-do my settings.yaml file from scratch because Searx just refused to start after upgrading to the latest commit.

**Describe the solution you'd like**
As a heavy Searx user, I would like to have the option to include a sub-config file that has my custom search engines set up in it.  That way, Searx can change all it wants, which includes the existing searx/searx/settings.yml file, but my custom search engines are isolated in their own file and won't make merging changes difficult.  Something to the effect of `#include /home/me/.config/exocortex/my-searx-settings.yml`

**Describe alternatives you've considered**
Creating and using a separate configuration file (searx/searx/my-settings.yml) instead of the existing one, but then merging in and debugging project-level changes is even more difficult.

**Additional context**
One example of what I mean by "custom search engines": https://drwho.virtadpt.net/archive/2020-11-30/interfacing-fess-with-searx/

**Comment by unixfox** [comment] 2021-04-26 21:32
Duplicate of https://github.com/searx/searx/issues/1209

**Closed as completed by unixfox** 2021-04-26 21:32 UTC
Labels: enhancement
