### ISSUE TITLE
Scraping Google in the client side

### ISSUE THREAD

**Issue by agnelvishal** [searx/searx#1608] opened 2019-05-27 19:17 UTC
Since Google introduces captcha when there are too many requests from an IP ( https://github.com/asciimoo/searx/issues/729), it might be better to scrape Google in the client side. This will also decrease server load.

**Comment by unixfox** [comment] 2019-05-28 14:10
This seems to be quite difficult to implement and probably out of the scope of Searx.

It would require to when the page load, the client do a request with javascript to fetch the Google results then generate a new HTML code and finally inject it into the page.

I'm pretty sure it would add quite a lot of delay and complexity.

The main issue is not the captcha of Google but it's bots that abuse the public Searx instances. If we get rid of these bots we wouldn't have any issue with Google like I already do on my instance : https://searx.be

**Comment by eggercomputerchaos** [comment] 2019-05-29 09:54
@unixfox 
nice,
how did you did get rid of these bots?

**Comment by unixfox** [comment] 2019-05-29 12:14
@eggercomputerchaos I talked about it here: https://github.com/asciimoo/searx/issues/1584#issuecomment-493596451 and here: https://github.com/asciimoo/searx/pull/1034#issuecomment-495917307

**Comment by eggercomputerchaos** [comment] 2019-05-29 12:42
@unixfox 
<Meanwhile, you can use my Searx instance: https://searx.be. It works by default with Google without any issue.>
thx

**Comment by marmistrz** [comment] 2019-09-15 09:14
Would it be possible just solve the captcha on the client side?

**Comment by agnelvishal** [comment] 2019-09-16 14:23
This code will scrape results from Google in client
```
function main() {
    var urls = document.querySelectorAll(".r a[target='_blank']:not(.fl)");;
    if (urls.length != 0) {
        var urlList = {};
        for (let i = 0; i < urls.length; i++) {
            url = urls[i].href;
            urlList[i] = url
        }
console.log(urlList)
}
```

**Comment by eggercomputerchaos** [comment] 2019-09-16 17:27
@agnelvishal 
thx
where to insert the code?

**Comment by agnelvishal** [comment] 2019-09-16 18:16
The integration is yet to be implemented

**Comment by eggercomputerchaos** [comment] 2019-09-16 20:19
ok, but in which file can I insert the code, or is it more complicated than I think?

**Comment by return42** [comment] 2019-11-30 15:28
> This code will scrape results from Google in client

Where is the sense in? .. parsing in the WEB-client?

**Comment by return42** [comment] 2019-11-30 15:33
> The main issue is not the captcha of Google but it's bots that abuse the public Searx instances. If we get rid of these bots we wouldn't have any issue with Google like I already do on my instance : https://searx.be

My experience is that just a group of more than one user can result in CAPTCHA questions or even one havey user.  Today it hits me at my instance https://darmarit.cloud/searx/ and  I checked the apache log: I was the only user, no bots at this time (today).

**Comment by return42** [comment] 2019-12-06 13:52
Update: now old google UI is completely dead https://github.com/asciimoo/searx/issues/1748#issuecomment-562549293

**Comment by unixfox** [comment] 2019-12-06 14:59
This issue isn't really about the old UI but about parsing the (new) UI from the client side.

**Comment by return42** [comment] 2019-12-06 16:43
Aaargh, my fail .. so many open issues / I got confused.

Anyway parsing in the client is nonsense / the solution for the new UI is https://github.com/asciimoo/searx/pull/1628 / or did I missed something .. again :)

**Comment by agnelvishal** [comment] 2019-12-09 15:08
> This seems to be quite difficult to implement and probably out of the scope of Searx.
> 
> It would require to when the page load, the client do a request with javascript to fetch the Google results then generate a new HTML code and finally inject it into the page.
> 
> I'm pretty sure it would add quite a lot of delay and complexity.
> 
> The main issue is not the captcha of Google but it's bots that abuse the public Searx instances. If we get rid of these bots we wouldn't have any issue with Google like I already do on my instance : https://searx.be

If scraping is done in the client side, that will prevent bot abuse. Because the bot will have to send request to Google search etc.

**Comment by jingyu9575** [comment] 2019-12-09 15:26
@agnelvishal Is it possible to do it in the client side? I'm not sure whether there are same-origin policies limiting it.

**Comment by unixfox** [comment] 2019-12-09 15:44
@agnelvishal we already know the benefits of parsing using the client side, I completely agree with you that it would be really great for Searx instances.
But the issue is that for Google we can't actually force the browser to do requests to `google.com` due to the `Same-origin` policy: https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

@asciimoo @return42 I guess you can close this issue because it's technically not possible to do what have been requested.

**Closed as completed** 2019-12-09 17:22 UTC
