### ISSUE TITLE
Feature request: ban cloudfire-infected sites

### ISSUE THREAD

**Issue by lua-rocks** [searx/searx#3077] opened 2021-11-29 22:33 UTC
Hello. I'm a tor user and half of my search requests in any search engine shows me the sites that asking to enter captcha. This is mostly h-captcha from cloudfire. Can you please add the option to ban all such sites and never show them in results? Thank you.

**Comment by unixfox** [comment] 2021-11-29 22:55
Duplicate of https://github.com/searx/searx/issues/1987

**Closed as completed by unixfox** 2021-11-29 22:55 UTC
