### ISSUE TITLE
Add baidu search engine

### ISSUE THREAD

**Issue by 2947452532** [searx/searx#2842] opened 2021-06-14 04:20 UTC
**Working URL to the engine**
https://www.baidu.com/

**Why do you want to add this engine?**

**Features of this engine**

**How can Searx fetch the information from this engine?**
name : baidu
engine : json_engine
paging : True
first_page_num : 0
search_url : https://www.baidu.com/s?tn=json&wd={query}&pn={pageno}&rn=50
url_query : url
title_query : title
content_query : abs
categories : general

**Applicable category of this engine**
general

**Additional context**

**Comment by unixfox** [comment] 2021-06-14 07:39
Duplicate of https://github.com/searx/searx/issues/1432

**Closed as completed by unixfox** 2021-06-14 07:39 UTC
Labels: enhancement, engine request
