### ISSUE TITLE
Fetching results from specific sources

### ISSUE THREAD

**Issue by arda618** [searx/searx#3502] opened 2023-04-25 11:25 UTC
I want to modify the source code of my SearXNG or SearX instance to get results only from the websites of my wish (what I mean is NOT an engine, but a website that contains searchable data). Let's say I only have Google enabled and I only want a list of websites to be indexed, and ignore all the other results that are not from the websites that I've listed. What do I have to do to achieve that?

**Comment by unixfox** [comment] 2023-04-25 13:44
Duplicate of https://github.com/searx/searx/issues/2952

**Closed as not planned by unixfox** 2023-04-25 13:44 UTC
Labels: duplicate, enhancement
