### ISSUE TITLE
"Rate Limit Exceeded" bug, search term "downloader"

### ISSUE THREAD

**Issue by Technically-Alexander** [searx/searx#1422] opened 2018-10-21 08:32 UTC
From Chrom/e/ium, it seems to be very consistent, that searches from the URL bar for the exact search phrase "crx downloader", in fact, any search phrase with the term "downloader" in it seems to get flagged down and send me to a "rate limit exceeded" page.  But when submitted from the website itself, and not the Chrom/e/ium search bar, it works just fine.  
I have tried ungoogled-chromium, true Chromium, and Google Chrome, and all have the same results.  This is not just the browser denying me for submitting X requests in Y amount of time, I can change the term and instantly get results, and change it back and instantly get "rate limit exceeded" again.

**Comment by miicha** [comment] 2018-10-29 14:39
I guess, it's about searx.me?
Blocking with filtron seems to be enabled. My guess would be, that "downloader" via GET requests is blockt much stricter than via POST requests. Since the default values on the website are POST (for the search formular) you can search from the search formular, but possibly your browser added searx.me with GET requests. Therefore it might help to remove the search engine and add it again.

**Comment by unixfox** [comment] 2019-07-17 12:06
I'm unable to reproduce the bug on searx.me
What do you think about closing this issue @dalf?

**Comment by dalf** [comment] 2019-07-17 12:27
@Technically-Alexander I close the issue, as @unixfox  I can't repoduce the bug.
If you re-open the bug, please include your comment, the searx instance url.

**Closed as completed by dalf** 2019-07-17 12:27 UTC
