### ISSUE TITLE
Language incompatibility

### ISSUE THREAD

**Issue by vnwnv** [searx/searx#1523] opened 2019-03-02 18:02 UTC
Hi! there is something wrong with Chinese.
When i set the Chinese as the interface language,  the preferences page return Internal Server Error.

**Comment by jfowl** [comment] 2019-03-03 17:32
On which instance did you try this?
Could you send us a screenshot of that error page?

**Comment by MarcAbonce** [comment] 2019-04-10 19:07
This is a duplicate of #1502.

**Closed as completed** 2019-12-21 20:32 UTC
Labels: duplicate
