### ISSUE TITLE
obsolete search results

### ISSUE THREAD

**Issue by ghost** [searx/searx#1255] opened 2018-03-31 05:28 UTC
![2018-03-31-adblock - searx me](https://user-images.githubusercontent.com/5884000/38159961-9031773a-34b4-11e8-9a08-fd162702eeb6.png)
`https://searx.me/?q=adblock&categories=general&time_range=day&language=pl-PL`

---

![2018-03-31-co polecacie do blokowania reklam w chrome_ - roykil - wykop pl](https://user-images.githubusercontent.com/5884000/38159979-e9fa1c04-34b4-11e8-9176-a3afdd63f2a0.png)
`https://www.wykop.pl/wpis/22576489/co-polecacie-do-blokowania-reklam-w-chrome-adblock/`

results from last year

**Comment by Zero3K** [comment] 2018-05-13 22:36
That's not good. I hope that it gets fixed soon.

**Comment by Pofilo** [comment] 2018-05-14 07:46
> That's not good. I hope that it gets fixed soon.

You can see that nothing has be done regarding this bug, it's "normal" that it's not fixed yet.
Feel free to open a PR :)

**Comment by unixfox** [comment] 2020-08-09 18:51
@KonoromiHimaries Are you still able to reproduce the issue? We reworked the Google engine multiple times since you opened this issue.

**Comment by unixfox** [comment] 2020-09-22 14:09
I'm closing this issue because the Google engine was reworked a lot since the creation of this issue.
Reopen this issue if you are still encountering this issue.

**Closed as completed by unixfox** 2020-09-22 14:09 UTC
