### ISSUE TITLE
creating .deb package

### ISSUE THREAD

**Issue by pointhi** [searx/searx#148] opened 2014-12-14 20:22 UTC
It would be greate if we add the posibility to create .deb packages to provide an easy install and automatic updatable version of searx.

https://wiki.debian.org/Python/Packaging

**Comment by dalf** [comment] 2015-03-04 18:09
I don't know how to do that : 
- the Debian are released are slow
- searx is evolving fast

If we rely on the python packages from Debian we will have to
- probably maintain two branches for compatibility issues. I think we will have more issue than the is_redirect one since [requests version of the stable Debian](https://packages.debian.org/wheezy/python-requests) is old.
- have some automatic tests to check if the package is working correctly (install, upgrade, etc...).

But the other (ugly) way means that searx package will embedded all the dependencies. It's the exact oposite of [Debian spirit](https://wiki.debian.org/Python/LibraryStyleGuide#Build-Depends).

I've never created a debian package including python code, so may be this is dumb question.

**Comment by Cqoicebordel** [comment] 2015-03-04 18:14
It could also be done in a PPA, so we wouldn't be tied to Debian release schedule.

**Comment by pointhi** [comment] 2015-03-04 18:15
.deb Packages are only one of the different packaging system. Beside Debian also Ubuntu and many other distributions use it. We can publish .deb packages with every new version of searx, and use a project ppa to delivere that new version. (Probably with up-to-date dependencies)

**Comment by dalf** [comment] 2015-03-04 21:54
I agree about a PPA but what about the dependencies ?
New version of the dependencies as .deb in the PPA ?

**Comment by pointhi** [comment] 2015-03-04 22:14
it's an idea. Otherwise we could probably use pip to get the packages up-to-date. But I have not the experience if that would be a good idea.

**Comment by Cqoicebordel** [comment] 2015-03-04 22:30
A deb is a bunch of folders to copy, and a script to execute. So if we choosed to create a deb file to install searx inside apache as described in the wiki, it would be relatively easy (-> copy paste everything from the wiki in the script, including the pip commands).

The issue here is that we can install searx a bunch of different ways : apache, nginx, xxx.xx/ or xxx.xx/searx, using a virtual-env, using a webserver or directly executing `python searx/webapp.py`, using supervisorctl...

So what is difficult is to build a script that can do everything, and ask the user. Or maybe, make a choice for the user. Or maybe...  
So also, what is difficult, is to take a decision...

To answer the other question, the dependencies are already taken care of by doing the apt-get install in the wiki. For the python packages, they are not dependencies, but are installed with pip during the installation.  
So .deb -> depend from pip (we need it to install python packages), and others
script.sh in deb -> install requests etc. using pip.

**Comment by dalf** [comment] 2015-03-04 23:36
Why not a package for each case :
- searx dependencies : see Installation wiki page
- searx-uwsgi depends on searx, uwsgi and uwsgi-plugin-python 
- searx-uwsgi-nginx depends on searx-uwsgi and nginx
- searx-uwsgi-apache depends on searx-uwsgi and apache2

About searx package, we have to try, because according to https://wiki.debian.org/Python/LibraryStyleGuide#Build-Depends : 

> ... This is a huge no-no, and pybuild internally sets the http_proxy and https_proxy environment variables (to 127.0.0.1:9) to prevent this from happening. 
> it will not work, at least with setup.py.

One solution : the package can contains everything, source code and the virtualenv.  

In this case, we can split the searx package into : 
- searx : only the searx source code, and depend on searx-env
- searx-env : the virtualenv (48Mo for mine, may be there is some extra things) 

EDIT : there is lxml which is compiled, and then it's start to be complicated...
EDIT2 : see http://dh-virtualenv.readthedocs.org/en/latest/info.html

**Comment by josch** [comment] 2017-01-04 15:04
Hi, I'm a Debian developer who is currently looking into packaging searx for Debian. I found this issue and wonder:

 * is this particular issue about just create a .deb package that you then distribute to users of Debian and its derivative or
 * is this issue about creating a package that complies with the Debian policies and guidelines so that it can be distributed by Debian and thus also its derivatives?

If your goal is the former, then issues like:

 - Debian doesn't allow downloading of anything during package build
 - Debian doesn't allow embedded code copies
 - Debian releases only every other year and expects certain versions to be supported during that time even if there are new releases by upstream
 - Debian might contain versions of libraries that are too old or too new
 - Upgrades must work even across multiple versions

will be irrelevant for your use case as you can easily create a .deb package that ignores all these issues and instead bundles up everything you need into one single directory structure that is then unpacked on the host system.

I thought this is what you want but then several of the former posts bring up the several packaging policies from the Debian wiki which should be irrevelant for this use case.

Since I'm currently working on a package that complies with Debian policies such that it can be uploaded to Debian proper I can give some of my own experiences (and questions) here:

 - Since Debian is trying to throw Python2 out I'm using the py3 branch of searx
 - Installing the following dependencies from Debian Stretch seems to make searx work perfectly: `nginx  uwsgi uwsgi-plugin-python3 python3-requests python3-certifi python3-yaml python3-pygments python3-werkzeug python3-flask python3-flask-babel python3-lxml python3-dateutil python3-openssl python3-ndg-httpsclient python3-pyasn1`
 - I only change the secret in the settings.yaml do I have to change anything else to distribute the result? In particular, do I have to change the `port`, `bind_address` or `base_url` settings when running searx behind uwsgi? It seems to run fine with the defaults.
 - searx seems to work fine out of a directory that it cannot write to. Does searx really not write any logs or caches to anywhere? This would make the "upgrade problem" really easy as there is no data to either convert or regenerate once a new version gets installed.

Thanks!

cheers, josch

**Comment by dalf** [comment] 2017-01-06 13:25
> Installing the following dependencies from Debian Stretch seems to make searx work perfectly: nginx uwsgi uwsgi-plugin-python3 python3-requests python3-certifi python3-yaml python3-pygments python3-werkzeug python3-flask python3-flask-babel python3-lxml python3-dateutil python3-openssl python3-ndg-httpsclient python3-pyasn1
* I think python3-pyasn1-modules is missing (0.0.8 in requirements.txt, 0.0.7 in unstable)
* python3-certifi is based on version 2016.2.28 in unstable (instead of 2016.9.26). I don't know how this package is maintained ?  

> I only change the secret in the settings.yaml do I have to change anything else to distribute the result? In particular, do I have to change the port, bind_address or base_url settings when running searx behind uwsgi? It seems to run fine with the defaults.
* the base_url has to changed if searx is not served at the root of the HTTP server.
* bind_address and port can be anything as long the HTTP server (apache, nginx, h2o, haproxy...) uses this (bind_address, port) tuple.
* other settings are ok, see :
https://asciimoo.github.io/searx/dev/install/installation.html#installation
and https://github.com/asciimoo/searx/wiki/Searx-with-haproxy

If there is an apache / nginx configuration, it would be good to add some HTTP headers to increase the security. See https://github.com/asciimoo/searx/wiki/Searx-with-haproxy#security 

Still about HTTP front-end, It would be good to encourage / force SSL, I don't know if it is possible ? 

> searx seems to work fine out of a directory that it cannot write to. Does searx really not write any logs or caches to anywhere? This would make the "upgrade problem" really easy as there is no data to either convert or regenerate once a new version gets installed.
searx doesn't write any logs except the one recorded from the ```logging``` module. The not merged PR #739 creates a temporary file into /tmp.

About maintenance : if an engine changed its API, the searx has to be changed otherwise searx can't use anymore this engine. Can the changes be backported to the debian package even into the stable version ? If the changes can't be backported, the searx stable version will be less and less usable.

**Comment by josch** [comment] 2017-01-06 13:47
Hi,

Quoting Alexandre Flament (2017-01-06 14:25:53)
> * I think python3-pyasn1-modules is missing (0.0.8 in requirements.txt, 0.0.7 in unstable)

I do not have that package installed at all but searx seems to work fine for
me. I cannot see any "from pyasn1 import modules" anywhere in the code. Which
parts are supposed to break without the python3-pyasn1-modules package?

> * python3-certifi is based on version 2016.2.28 in unstable (instead of
> 2016.9.26). I don't know how this package is maintained ?

I'm not familiar with the package but again there seem to be no problems
despite the older version. If you tell me how to reproduce a problem introduced
due to the outdated version, then I can upload a newer version of
python3-certifi into unstable.

> * the base_url has to changed if searx is not served at the root of the HTTP server.
> * bind_address and port can be anything as long the HTTP server (apache, nginx, h2o, haproxy...) uses this (bind_address, port) tuple.
> * other settings are ok, see :
> https://asciimoo.github.io/searx/dev/install/installation.html#installation
> and https://github.com/asciimoo/searx/wiki/Searx-with-haproxy
> 
> If there is an apache / nginx configuration, it would be good to add some HTTP headers to increase the security. See https://github.com/asciimoo/searx/wiki/Searx-with-haproxy#security 
> 
> Still about HTTP front-end, It would be good to encourage / force SSL, I don't know if it is possible ?

I talked with some fellow Debian Developers about this topic yesterday. It
seems that because consumers of the package will have very heterogeneous
requirements regarding their setup, the preferred way of shipping the service
is to not enable it by default after installation but to instead provide enough
tools that help the user to set everything up correctly. Another way to handle
this would be to ask the user on installation time about the setup they want to
use. The disadvantage about this approach is that one then has to cover *all*
the important use cases which easily lets the complexity of such a setup
skyrocket, especially taking upgrades into account. Thus, to keep it simple, my
plan was to provide default configuration files with helpful comments for a
uwsgi/nginx setup. After installing the package, the user then just has to copy
these files into the right location and restart uwsgi. Does this sound like a
good solution to you?

> About maintenance : if an engine changed its API, the searx has to be changed
> otherwise searx can't use anymore this engine. Can the changes be backported
> to the debian package even into the stable version ? If the changes can't be
> backported, the searx stable version will be less and less usable.

We have a number of packages with such characteristics in Debian already. Think
of software like youtube-dl and the like. There are two ways to deal with this.
One is to upload the fixed version to the `stable-updates` distribution:
https://wiki.debian.org/StableUpdates With that the fixed package will be made
available easily to users of Debian stable.

And then there is the possibility of using stable-backports which are usually
used to not just contain the same package version as in stable but with fixes
applied but to contain completely new package versions.

Thanks!

cheers, josch

**Comment by josch** [comment] 2017-01-07 02:05
I packaged the current tip of the py3 branch (commit 94b99def). The only missing things are:

 - filling `README.Debian` with Debian-specific instructions how to get things running
 - adjusting `debian/copyright`
 - writing an ITP bug and closing that bug in `debian/changelog`

But technically, the package already works and is nearly Debian policy compliant (minus the three items mentioned above). If you know what you are doing, you can get the package here:

https://mentors.debian.net/package/searx

The package comes with seven Debian-specific patches and deletes 170 files from the original source. Maybe we can reduce these numbers but I'll open a separate issue about that at a later point.

**Comment by josch** [comment] 2017-01-07 17:59
I now handled the last three remaining bits and updated the version at mentors.debian.net with these changes.

I plan to upload the package to Debian unstable once you make a release that includes the py3 branch.

My packaging is still using environment variables for the custom static and template directories (see issue #815) but as I see from pull request #816 you will probably end up putting these settings into the config file.

Thanks!

cheers, josch

**Comment by dalf** [comment] 2017-01-07 18:33
Great ! Thank you.

Hum one question : https://browse.dgit.debian.org/searx.git/ seems to be empty ?

**Comment by josch** [comment] 2017-01-07 19:16
The `Vcs-Git` and `Vcs-Browser` headers contain the urls where the packaging repository can be accessed. I plan to use dgit (as can be seen from the url) so that repository will only become available once I do the first upload. I put the header in nevertheless already because it's something that is easily forgotten (there exists no lintian warning about it, for example).

**Comment by josch** [comment] 2017-05-28 17:27
Now that issue #63 is fixed I guess the next release will be including python 3 support? If somebody could give me a heads-up in this issue once the searx release with python3 support happens, I can upload the searx Debian package to the Debian NEW queue.

**Comment by kvch** [comment] 2017-05-30 18:20
@josch The next release will contain Python3 support. However, I don't know when the next release is coming out. Now @asciimoo releases searx, so the release date depends on him.

**Comment by josch** [comment] 2017-06-19 14:30
I uploaded a package to the Debian NEW queue:

https://ftp-master.debian.org/new/searx_0.12.0+dfsg1-1.html

It will be added to Debian unstable once it has been reviewed by the FTP master team.

**Comment by dalf** [comment] 2017-11-26 15:49
@josch : One note the python3-searx debian package in sid : python3-ndg-httpsclient and python3-pyasn1 are declared necessary. From the PIP point of view, these two packages used to be dependencies of requests, but the version 2.18.1 doesn't need them anymore.

**Comment by dalf** [comment] 2017-12-07 12:15
https://packages.debian.org/source/sid/searx

see #1091

**Closed as completed by dalf** 2017-12-07 12:15 UTC
Labels: enhancement, installation, meta, debian
