### ISSUE TITLE
Search engine policies and Searx

### ISSUE THREAD

**Issue by steckerhalter** [searx/searx#1641] opened 2019-07-18 08:21 UTC
So I was wondering if the aggregation of search results like Searx is doing it is not against search engine policies. Does e.g. Google or DDG etc. allow a metasearch engine to use their results like this? What is your take on this?
Sorry if this has been already written somewhere but I couldn't find anything.

**Comment by unixfox** [comment] 2021-01-04 15:02
Duplicate of https://github.com/searx/searx/issues/1237

**Closed as completed by unixfox** 2021-01-04 15:02 UTC
