### ISSUE TITLE
bang! functionality only working as first argument

### ISSUE THREAD

**Issue by tobiasnix** [searx/searx#440] opened 2015-09-24 08:24 UTC
eg. on my local installation `!go foo` will give google only results as expected but `foo !go` will not.

Is it right that !bang functionality will just work if its used as first argument? Afaik on duckduckgo it doesn't matter on which position !bang words are used.

**Comment by vindarel** [comment] 2016-10-13 14:22
Looks like a duplicate of https://github.com/asciimoo/searx/issues/363 (+1!)

**Closed as completed** 2016-10-14 06:17 UTC
Labels: enhancement, ui / ux
