### ISSUE TITLE
fedisearch

### ISSUE THREAD

**Issue by programizer** [searx/searx#2704] opened 2021-03-30 08:11 UTC
**Working URL to the engine**

https://fedisearch.com/

**Why do you want to add this engine?**

It searches posts from the Fediverse! Regular web search engines can't do that properly, because they just have a small random set of posts in their cache that happened to be on the instance front page at the time of crawling.

**Features of this engine**

At the moment only working fedi search engine afaik. The only other one is down.

**How can Searx fetch the information from this engine?**

https://fedisearch.com/search?q=foo&commit=Search

**Applicable category of this engine**

social media

**Additional context**

fedi is an important contribution to re-decentralizing the web.

**Comment by return42** [comment] 2021-03-30 08:18
Duplicate of #2335 and #906 / read comments at ...

[What is the advantage of Fedisearch compared to other search sides? IMO Fedisearch is crap .. but if someone wants to implement an searx-engine for .. why not.](https://github.com/searx/searx/issues/2335#issuecomment-767817724)

**Comment by programizer** [comment] 2021-03-30 08:50
> what is the advantage?  

It's the only one.

> Fedisearch is crap  

It's the only one.

I'm not here to tell you what to do. Maybe I'll figure out how to do it myself...

In case you don't know what the Fediverse is:  
https://fediverse.party/

**Comment by return42** [comment] 2021-03-30 09:05
> I'm not here to tell you what to do. Maybe I'll figure out how to do it myself...

preparing a PR would be nice / thanks!

This issue is a duplicate / can you please close this issue and give #906 the preference.

**Closed as completed** 2021-04-01 16:30 UTC
Labels: duplicate, enhancement, engine request
