### ISSUE TITLE
Sometimes no results are shown

### ISSUE THREAD

**Issue by ghost** [searx/searx#1793] opened 2020-01-02 09:59 UTC
Hello! I have decided to run my own private Searx instance, where I haven't altered the default settings much, save for selecting different engines to use and increasing max time to 4 seconds. However, I have experienced the following issue with some public instances as well:

When I search for pretty much any text (e.g. ‘GNU+Linux screen recorders’ worked for me), I get one of these three outcomes:

* Numerous results are shown as expected.
* ‘Sorry! we didn't find any results. Please use another query or search in more categories.’
* ‘Error! Engines cannot retrieve results.’ ‘duckduckgo (timeout)’ ‘Please, try again later or find another searx instance.’

The first outcome seems to happen the least frequently. If I search for a name or a common term (e.g. ‘penguin’), I often get results from Wikipedia and Wikidata only. Repeating the search several times can work for forcing the first outcome eventually.

I'm running Searx 0.15.0 on [Parabola GNU+Linux-libre](https://www.parabola.nu/) and I browse with [GNUzilla Icecat 68.3.0](https://www.gnu.org/software/gnuzilla/). Please let me know if I can provide other information to help tracing this issue.

**Comment by unixfox** [comment] 2020-01-02 10:06
If you are running an older version of Searx, I'm sorry that version is too old to keep using without expecting huge amount of bugs.
You should do an installation from the latest code using this guide: https://asciimoo.github.io/searx/admin/installation.html

After that let me know if you still encounter bugs.

**Comment by return42** [comment] 2020-01-02 13:29
FYI: may this post is also useful for you https://github.com/asciimoo/searx/issues/1792#issuecomment-570203111

**Comment by chaosmonk1** [comment] 2020-01-02 13:34
> ‘Sorry! we didn't find any results. Please use another query or search in more categories.’

I recently reported the same issue.  At return42's advice I installed from git, and so far it seems the issue is fixed.

**Comment by unixfox** [comment] 2020-01-02 14:15
@return42 probably good to close this issue

**Closed as completed** 2020-01-02 14:17 UTC
