### ISSUE TITLE
Save settings as links

### ISSUE THREAD

**Issue by ShalokShalom** [searx/searx#946] opened 2017-06-15 10:59 UTC
I am totally for this method, which gets offered by both; DuckDuckGo and Startpage/ixQuick:

Save the settings to a specific URL, in order to share them and make it super secure, without any cookies. 

Here are some use cases:

1) I think Pointhi is a bit more clear as the default theme. The first impression counts.

2) The local settings do not apply with secure browsers like TOR. (Plus they even do not apply in my case at all without manual invention, which is, of course, an own issue that can get resolved.)

3) Then, there is POST preset, which makes it impossible to share links. 

So all of this is currently a little bit a blocker for me, in order to recommend Searx to my crowd.

Thanks a lot in advance; genius project, seriously.

**Comment by dalf** [comment] 2017-06-18 13:58
Seems like a duplicate of #695

**Closed as completed** 2017-06-18 14:47 UTC
