### ISSUE TITLE
Mobile version doesn't show arrows for navigation

### ISSUE THREAD

**Issue by MykolaSauliak** [searx/searx#2778] opened 2021-04-24 20:20 UTC
**What happened?**
There are no arrows and page refreshing doesn't work, I can see only first results

**How To Reproduce**

Go to the searx.info from brave browser

**Expected behavior**

all results are visible like on desktop version

**Screenshots & Logs**
![Screenshot_20210424-181309](https://user-images.githubusercontent.com/16925900/115971845-7fcde280-a553-11eb-967c-fb2edd3c37a1.png)

**Additional context**

**Comment by unixfox** [comment] 2021-04-24 20:24
Can you reproduce the same bug on Firefox on Android or Google Chrome/Chromium on Android?

**Comment by MykolaSauliak** [comment] 2021-04-24 21:05
@unixfox on google chrome and Firefox it works fine

**Comment by unixfox** [comment] 2021-04-24 21:16
It's an issue with Brave then and we can't do much about this sorry. You should report this bug to brave devs.

Nobody in the team use Brave so we haven't tested it, it should work tho because it's still a basic HTML page so that's a strange.

I'm closing this issue based on what I said.

**Closed as completed by unixfox** 2021-04-24 21:16 UTC
Labels: bug

**Comment by MykolaSauliak** [comment] 2021-04-25 15:24
It's only related to the oscar theme
question not about navigation
why you don't use Brave? are there any reasons to use chrome instead (from privacy perspective) ?

**Comment by unixfox** [comment] 2021-04-25 16:08
> It's only related to the oscar theme
> question not about navigation
> why you don't use Brave? are there any reasons to use chrome instead (from privacy perspective) ?

I'm using Firefox which is better in privacy than Brave and is not a fork of Chromium/Chrome.
